imagenet_models = {'convnext_small': 'ConvNeXt_Small_Weights.IMAGENET1K_V1', 
                   'convnext_tiny': 'ConvNeXt_Tiny_Weights.IMAGENET1K_V1', 
                   'densenet121': 'DenseNet121_Weights.IMAGENET1K_V1', 
                   'densenet161': 'DenseNet161_Weights.IMAGENET1K_V1', 
                   'densenet169': 'DenseNet169_Weights.IMAGENET1K_V1', 
                   'densenet201': 'DenseNet201_Weights.IMAGENET1K_V1', 
                   'googlenet': 'GoogLeNet_Weights.IMAGENET1K_V1', 
                   'inception_v3': 'Inception_V3_Weights.IMAGENET1K_V1', 
                   'mnasnet0_5': 'MNASNet0_5_Weights.IMAGENET1K_V1', 
                   'mnasnet0_75': 'MNASNet0_75_Weights.IMAGENET1K_V1', 
                   'mnasnet1_0': 'MNASNet1_0_Weights.IMAGENET1K_V1', 
                   'mnasnet1_3': 'MNASNet1_3_Weights.IMAGENET1K_V1', 
                   'mobilenet_v3_small': 'MobileNet_V3_Small_Weights.IMAGENET1K_V1', 
                   'mobilenet_v3_large': 'MobileNet_V3_Large_Weights.IMAGENET1K_V1', 
                   'regnet_x_16gf': 'RegNet_X_16GF_Weights.IMAGENET1K_V1', 
                   'regnet_x_1_6gf': 'RegNet_X_1_6GF_Weights.IMAGENET1K_V1', 
                   'regnet_x_3_2gf': 'RegNet_X_3_2GF_Weights.IMAGENET1K_V1', 
                   'regnet_x_400mf': 'RegNet_X_400MF_Weights.IMAGENET1K_V1', 
                   'regnet_x_800mf': 'RegNet_X_800MF_Weights.IMAGENET1K_V1', 
                   'regnet_x_8gf': 'RegNet_X_8GF_Weights.IMAGENET1K_V1', 
                   'regnet_y_1_6gf': 'RegNet_Y_1_6GF_Weights.IMAGENET1K_V1', 
                   'regnet_y_3_2gf': 'RegNet_Y_3_2GF_Weights.IMAGENET1K_V1', 
                   'regnet_y_400mf': 'RegNet_Y_400MF_Weights.IMAGENET1K_V1', 
                   'regnet_y_800mf': 'RegNet_Y_800MF_Weights.IMAGENET1K_V1', 
                   'regnet_y_8gf': 'RegNet_Y_8GF_Weights.IMAGENET1K_V1', 
                   'resnext50_32x4d': 'ResNeXt50_32X4D_Weights.IMAGENET1K_V1', 
                   'resnet101': 'ResNet101_Weights.IMAGENET1K_V1', 
                   'resnet18': 'ResNet18_Weights.IMAGENET1K_V1', 
                   'resnet34': 'ResNet34_Weights.IMAGENET1K_V1', 
                   'resnet50': 'ResNet50_Weights.IMAGENET1K_V1', 
                   'shufflenet_v2_x0_5': 'ShuffleNet_V2_X0_5_Weights.IMAGENET1K_V1', 
                   'shufflenet_v2_x1_0': 'ShuffleNet_V2_X1_0_Weights.IMAGENET1K_V1', 
                   'shufflenet_v2_x1_5': 'ShuffleNet_V2_X1_5_Weights.IMAGENET1K_V1', 
                   'shufflenet_v2_x2_0': 'ShuffleNet_V2_X2_0_Weights.IMAGENET1K_V1',
                   'swin_s': 'Swin_S_Weights.IMAGENET1K_V1', 
                   'swin_t': 'Swin_T_Weights.IMAGENET1K_V1', 
                   'swin_v2_s': 'Swin_V2_S_Weights.IMAGENET1K_V1', 
                   'swin_v2_t': 'Swin_V2_T_Weights.IMAGENET1K_V1'}



cifar10_models = (
        'mobilenetv2_x0_5',
        'mobilenetv2_x0_75',
        'mobilenetv2_x1_0',
        'mobilenetv2_x1_4',
        'repvgg_a0',
        'repvgg_a1',
        'repvgg_a2',
        'resnet20',
        'resnet32',
        'resnet44',
        'resnet56',
        'shufflenetv2_x0_5',
        'shufflenetv2_x1_0',
        'shufflenetv2_x1_5',
        'shufflenetv2_x2_0',
        'vgg11_bn',
        'vgg13_bn',
        'vgg16_bn',
        'vgg19_bn'
        )